export const countries = [
  { value:  'Afghanistan', label:  'Afghanistan' },
  { value:  'Albania', label:  'Albania' },
  { value:  'Algeria', label:  'Algeria' },
  { value:  'Andorra', label:  'Andorra' },
  { value:  'Angola', label:  'Angola' },
  { value:  'Antigua And Barbuda', label:  'Antigua and Barbuda' },
  { value:  'Argentina', label:  'Argentina' },
  { value:  'Armenia', label:  'Armenia' },
  { value:  'Australia', label:  'Australia' },
  { value:  'Austria', label:  'Austria' },
  { value:  'Azerbaijan', label:  'Azerbaijan' },
  { value:  'Bahamas', label:  'Bahamas' },
  { value:  'Bahrain', label:  'Bahrain' },
  { value:  'Bangladesh', label:  'Bangladesh' },
  { value:  'Barbados', label:  'Barbados' },
  { value:  'Belarus', label:  'Belarus' },
  { value:  'Belgium', label:  'Belgium' },
  { value:  'Belize', label:  'Belize' },
  { value:  'Benin', label:  'Benin' },
  { value:  'Bhutan', label:  'Bhutan' },
  { value:  'Bolivia', label:  'Bolivia' },
  { value:  'Bosniaherzegovina', label:  'Bosnia and Herzegovina' },
  { value:  'Botswana', label:  'Botswana' },
  { value:  'Brazil', label:  'Brazil' },
  { value:  'Brunei', label:  'Brunei' },
  { value:  'Bulgaria', label:  'Bulgaria' },
  { value:  'Burkinafaso', label:  'Burkina Faso' },
  { value:  'Burundi', label:  'Burundi' },
  { value:  'Capeverde', label:  'Cape Verde' },
  { value:  'Cambodia', label:  'Cambodia' },
  { value:  'Cameroon', label:  'Cameroon' },
  { value:  'Canada', label:  'Canada' },
  { value:  'Chad', label:  'Chad' },
  { value:  'Chile', label:  'Chile' },
  { value:  'China', label:  'China PR' },
  { value:  'Colombia', label:  'Colombia' },
  { value:  'Comoros', label:  'Comoros' },
  { value:  'Congo', label:  'Congo' },
  { value:  'CongoDR', label:  'Congo DR' },
  { value:  'CookIslands', label:  'Cook Islands' },
  { value:  'CostaRica', label:  'Costa Rica' },
  { value:  'Croatia', label:  'Croatia' },
  { value:  'Cuba', label:  'Cuba' },
  { value:  'Cyprus', label:  'Cyprus' },
  { value:  'CzechRepublic', label:  'Czech Republic' },
  { value:  'Denmark', label:  'Denmark' },
  { value:  'Djibouti', label:  'Djibouti' },
  { value:  'Dominica', label:  'Dominica' },
  { value:  'DominicanRepublic', label:  'Dominican Republic' },
  { value:  'Ecuador', label:  'Ecuador' },
  { value:  'Egypt', label:  'Egypt' },
  { value:  'ElSalvador', label:  'El Salvador' },
  { value:  'England', label:  'England' },
  { value:  'EquatorialGuinea', label:  'Equatorial Guinea' },
  { value:  'Eritrea', label:  'Eritrea' },
  { value:  'Estonia', label:  'Estonia' },
  { value:  'Eswatini', label:  'Eswatini' },
  { value:  'Ethiopia', label:  'Ethiopia' },
  { value: 'faroeIslands', label: 'Faroe Islands' },
  { value: 'fiji', label: 'Fiji' },
  { value: 'finland', label: 'Finland' },
  { value: 'france', label: 'France' },
  { value: 'gabon', label: 'Gabon' },
  { value: 'gambia', label: 'Gambia' },
  { value: 'georgia', label: 'Georgia' },
  { value: 'germany', label: 'Germany' },
  { value: 'ghana', label: 'Ghana' },
  { value: 'gibraltar', label: 'Gibraltar' },
  { value: 'greece', label: 'Greece' },
  { value: 'grenada', label: 'Grenada' },
  { value: 'guam', label: 'Guam' },
  { value: 'guatemala', label: 'Guatemala' },
  { value: 'guinea', label: 'Guinea' },
  { value: 'guineaBissau', label: 'Guinea-Bissau' },
  { value: 'guyana', label: 'Guyana' },
  { value: 'haiti', label: 'Haiti' },
  { value: 'honduras', label: 'Honduras' },
  { value: 'hongKong', label: 'Hong Kong' },
  { value: 'hungary', label: 'Hungary' },
  { value: 'iceland', label: 'Iceland' },
  { value: 'india', label: 'India' },
  { value: 'indonesia', label: 'Indonesia' },
  { value: 'iran', label: 'IR Iran' },
  { value: 'iraq', label: 'Iraq' },
  { value: 'ireland', label: 'Republic of Ireland' },
  { value: 'israel', label: 'Israel' },
  { value: 'italy', label: 'Italy' },
  { value: 'ivoryCoast', label: 'Ivory Coast' },
  { value: 'jamaica', label: 'Jamaica' },
  { value: 'japan', label: 'Japan' },
  { value: 'jordan', label: 'Jordan' },
  { value: 'kazakhstan', label: 'Kazakhstan' },
  { value: 'kenya', label: 'Kenya' },
  { value: 'kiribati', label: 'Kiribati' },
  { value: 'kosovo', label: 'Kosovo' },
  { value: 'kuwait', label: 'Kuwait' },
  { value: 'kyrgyzstan', label: 'Kyrgyzstan' },
  { value: 'laos', label: 'Laos' },
  { value: 'latvia', label: 'Latvia' },
  { value: 'lebanon', label: 'Lebanon' },
  { value: 'lesotho', label: 'Lesotho' },
  { value: 'liberia', label: 'Liberia' },
  { value: 'libya', label: 'Libya' },
  { value: 'liechtenstein', label: 'Liechtenstein' },
  { value: 'lithuania', label: 'Lithuania' },
  { value: 'luxembourg', label: 'Luxembourg' },
  { value: 'macau', label: 'Macau' },
  { value: 'madagascar', label: 'Madagascar' },
  { value: 'malawi', label: 'Malawi' },
  { value: 'malaysia', label: 'Malaysia' },
  { value: 'maldives', label: 'Maldives' },
  { value: 'mali', label: 'Mali' },
  { value: 'malta', label: 'Malta' },
  { value: 'marshallIslands', label: 'Marshall Islands' },
  { value: 'mauritania', label: 'Mauritania' },
  { value: 'mauritius', label: 'Mauritius' },
  { value: 'mexico', label: 'Mexico' },
  { value: 'micronesia', label: 'Micronesia' },
  { value: 'moldova', label: 'Moldova' },
  { value: 'monaco', label: 'Monaco' },
  { value: 'mongolia', label: 'Mongolia' },
  { value: 'montenegro', label: 'Montenegro' },
  { value: 'montserrat', label: 'Montserrat' },
  { value: 'morocco', label: 'Morocco' },
  { value: 'mozambique', label: 'Mozambique' },
  { value: 'myanmar', label: 'Myanmar' },
  { value: 'namibia', label: 'Namibia' },
  { value: 'nauru', label: 'Nauru' },
  { value: 'nepal', label: 'Nepal' },
  { value: 'netherlands', label: 'Netherlands' },
  { value: 'newCaledonia', label: 'New Caledonia' },
  { value: 'newZealand', label: 'New Zealand' },
  { value: 'nicaragua', label: 'Nicaragua' },
  { value: 'niger', label: 'Niger' },
  { value: 'nigeria', label: 'Nigeria' },
  { value: 'northKorea', label: 'North Korea' },
  { value: 'northMacedonia', label: 'North Macedonia' },
  { value: 'northernIreland', label: 'Northern Ireland' },
  { value: 'norway', label: 'Norway' },
  { value: 'oman', label: 'Oman' },
  { value: 'pakistan', label: 'Pakistan' },
  { value: 'palau', label: 'Palau' },
  { value: 'palestine', label: 'Palestine' },
  { value: 'panama', label: 'Panama' },
  { value: 'papuaNewGuinea', label: 'Papua New Guinea' },
  { value: 'paraguay', label: 'Paraguay' },
  { value: 'peru', label: 'Peru' },
  { value: 'philippines', label: 'Philippines' },
  { value: 'poland', label: 'Poland' },
  { value: 'portugal', label: 'Portugal' },
  { value: 'puertoRico', label: 'Puerto Rico' },
  { value: 'qatar', label: 'Qatar' },
  { value: 'romania', label: 'Romania' },
  { value: 'russia', label: 'Russia' },
  { value: 'rwanda', label: 'Rwanda' },
  { value: 'saintKittsandNevis', label: 'Saint Kitts and Nevis' },
  { value: 'saintLucia', label: 'Saint Lucia' },
  { value: 'saintVincentandtheGrenadines', label: 'Saint Vincent and the Grenadines' },
  { value: 'samoa', label: 'Samoa' },
  { value: 'sanMarino', label: 'San Marino' },
  { value: 'saoTomeandPrincipe', label: 'Sao Tome and Principe' },
  { value: 'saudiArabia', label: 'Saudi Arabia' },
  { value: 'scotland', label: 'Scotland' },
  { value: 'senegal', label: 'Senegal' },
  { value: 'serbia', label: 'Serbia' },
  { value: 'seychelles', label: 'Seychelles' },
  { value: 'sierraLeone', label: 'Sierra Leone' },
  { value: 'singapore', label: 'Singapore' },
  { value: 'slovakia', label: 'Slovakia' },
  { value: 'slovenia', label: 'Slovenia' },
  { value: 'solomonIslands', label: 'Solomon Islands' },
  { value: 'somalia', label: 'Somalia' },
  { value: 'southAfrica', label: 'South Africa' },
  { value: 'southKorea', label: 'South Korea' },
  { value: 'southSudan', label: 'South Sudan' },
  { value: 'spain', label: 'Spain' },
  { value: 'sriLanka', label: 'Sri Lanka' },
  { value: 'sudan', label: 'Sudan' },
  { value: 'suriname', label: 'Suriname' },
  { value: 'sweden', label: 'Sweden' },
  { value: 'switzerland', label: 'Switzerland' },
  { value: 'syria', label: 'Syria' },
  { value: 'taiwan', label:  'Chinese Taipei' },
  { value: 'tajikistan', label: 'Tajikistan' },
  { value: 'tanzania', label: 'Tanzania' },
  { value: 'thailand', label: 'Thailand' },
  { value: 'togo', label: 'Togo' },
  { value: 'tonga', label: 'Tonga' },
  { value: 'trinidadandTobago', label: 'Trinidad and Tobago' },
  { value: 'tunisia', label: 'Tunisia' },
  { value: 'turkey', label: 'Turkey' },
  { value: 'turkmenistan', label: 'Turkmenistan' },
  { value: 'tuvalu', label: 'Tuvalu' },
  { value: 'uganda', label: 'Uganda' },
  { value: 'ukraine', label: 'Ukraine' },
  { value: 'unitedArabEmirates', label: 'United Arab Emirates' },
  { value: 'unitedStates', label: 'United States' },
  { value: 'uruguay', label: 'Uruguay' },
  { value: 'uzbekistan', label: 'Uzbekistan' },
  { value: 'vanuatu', label: 'Vanuatu' },
  { value: 'aticanCity', label: 'Vatican City' },
  { value: 'Venezuela', label: 'Venezuela' },
  { value: 'Vietnam', label: 'Vietnam' },
  { value: 'Wales', label: 'Wales' },
  { value: 'Yemen', label: 'Yemen' },
  { value: 'Zambia', label: 'Zambia' },
  { value: 'Zimbabwe', label: 'Zimbabwe' }

];
